# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
workspace = "."
paths = [
    "formidable.php",
    "classes",
    "paypal",
    "stripe",
    "square",
    "tests",
]
includes = []
excludes = ["vendor", "node_modules", "mago"]
extensions = ["php"]

[formatter]
preset = "default"
use-tabs = true

[linter]
integrations = []

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
array-style = { enabled = false }
strict-types = { enabled = false }
no-else-clause = { enabled = false }
no-empty = { enabled = false }
no-global = { enabled = false }
identity-comparison = { enabled = false }
prefer-static-closure = { enabled = false }
prefer-arrow-function = { enabled = false }
class-name = { enabled = false }
no-sprintf-concat = { enabled = false }
prefer-early-continue = { enabled = false }
excessive-parameter-list = { enabled = false }
no-nested-ternary = { enabled = false }
braced-string-interpolation = { enabled = false }
combine-consecutive-issets = { enabled = false }
kan-defect = { enabled = false }
no-request-variable = { enabled = false }
too-many-methods = { enabled = false }
cyclomatic-complexity = { enabled = false }
tagged-todo = { enabled = false }
strict-behavior = { enabled = false }
loop-does-not-iterate = { enabled = false }
explicit-octal = { enabled = false }
no-redundant-math = { enabled = false }
no-error-control-operator = { enabled = false }
no-closing-tag = { enabled = false }
too-many-properties = { enabled = false }
sensitive-parameter = { enabled = false }
halstead = { enabled = false } # Consider enabling this soon.
use-compound-assignment = { enabled = false } # Consider enabling this soon.
require-preg-quote-delimiter = { enabled = false }
no-assign-in-condition = { enabled = false }
no-insecure-comparison = { enabled = false } # Consider enabling this soon.
excessive-nesting = { enabled = false } # Consider enabling this soon.
no-redundant-parentheses = { enabled = false } # Fix this first.
inline-variable-return = { enabled = false } # Fix this first.
no-redundant-method-override = { enabled = false } # Fix this first.

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true