# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
workspace = "."
paths = [
    "formidable.php",
    "classes",
    "paypal",
    "stripe",
    "square",
    "tests",
]
includes = []
excludes = ["vendor", "node_modules", "mago"]
extensions = ["php"]

[formatter]
preset = "default"
use-tabs = true

[linter]
integrations = []

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
array-style = { enabled = false }
strict-types = { enabled = false }
no-else-clause = { enabled = false }
no-empty = { enabled = false }
no-global = { enabled = false }
identity-comparison = { enabled = false }
prefer-static-closure = { enabled = false }
prefer-arrow-function = { enabled = false }
class-name = { enabled = false }
no-sprintf-concat = { enabled = false }
prefer-early-continue = { enabled = false }
excessive-parameter-list = { enabled = false }
no-nested-ternary = { enabled = false }
braced-string-interpolation = { enabled = false }
combine-consecutive-issets = { enabled = false }
kan-defect = { enabled = false }
no-request-variable = { enabled = false }
too-many-methods = { enabled = false }
cyclomatic-complexity = { enabled = false }
tagged-todo = { enabled = false }
strict-behavior = { enabled = false }
loop-does-not-iterate = { enabled = false }
explicit-octal = { enabled = false }
no-redundant-math = { enabled = false }
no-error-control-operator = { enabled = false }
no-closing-tag = { enabled = false }
too-many-properties = { enabled = false }
sensitive-parameter = { enabled = false }
halstead = { enabled = false } # Consider enabling this soon.
use-compound-assignment = { enabled = false } # Consider enabling this soon.
require-preg-quote-delimiter = { enabled = false }
no-assign-in-condition = { enabled = false }
no-insecure-comparison = { enabled = false } # Consider enabling this soon.
excessive-nesting = { enabled = false } # Consider enabling this soon.
no-redundant-method-override = { enabled = false } # Fix this first.

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
ignore = [
    "invalid-param-tag",
    "malformed-docblock-comment",
    "non-existent-function",
    "undefined-variable",
    "mixed-argument",
    "redundant-condition",
    "mixed-array-access",
    "mixed-operand",
    "mixed-property-access",
    "invalid-global",
    "possibly-false-argument",
    "unknown-class-instantiation",
    "unused-method",
    "non-existent-method",
    "invalid-return-statement",
    "invalid-iterator",
    "less-specific-nested-argument-type",
    "reference-to-undefined-variable",
    "mixed-return-statement",
    "redundant-logical-operation",
    "undefined-int-array-index",
    "possibly-invalid-argument",
    "mixed-assignment",
    "possibly-null-argument",
    "invalid-argument",
    "invalid-operand",
    "less-specific-return-statement",
    "non-existent-constant",
    "ambiguous-object-property-access",
    "less-specific-argument",
    "invalid-type-cast",
    "reference-constraint-violation",
    "possibly-false-operand",
    "nullable-return-statement",
    "array-to-string-conversion",
    "possibly-undefined-string-array-index",
    "redundant-comparison",
    "mixed-array-assignment",
    "generic-object-iteration",
    "mixed-method-access",
    "mixed-array-assignment",
    "redundant-type-comparison",
    "false-argument", # Fix this soon
    "mixed-property-type-coercion",
    "invalid-method-access",
    "possible-method-access-on-null",
    "possibly-null-property-access",
    "mixed-array-index",
    "less-specific-nested-return-statement",
    "null-operand",
    "invalid-property-access",
    "impossible-assignment",
    "non-existent-class",
    "never-return",
    "non-existent-class-like",
    "invalid-member-selector",
    "non-existent-property",
    "invalid-member-selector",
    "too-few-arguments",
    "impossible-type-comparison", # Fix this soon
    "string-member-selector",
    "impossible-condition",
    "falsable-return-statement",
    "property-type-coercion",
    "invalid-property-assignment-value",
    "unused-property",
    "possibly-undefined-variable",
    "impossible-nonnull-entry-check",
    "ambiguous-object-method-access",
    "null-array-index",
    "possibly-null-operand",
    "missing-return-statement",
    "incompatible-parameter-type",
    "null-array-access",
    "null-argument",
    "mismatched-array-index",
    "no-value",
    "possibly-invalid-operand",
    "non-documented-property",
    "conflicting-reference-constraint",
    "redundant-null-coalesce",
    "unsafe-instantiation",
    "invalid-destructuring-source",
    "unknown-iterator-type",
    "invalid-array-access",
    "undefined-variable-in-closure-use",
    "possibly-false-iterator",
    "invalid-unset",
    "redundant-isset-check",
    "possibly-invalid-iterator",
    "undefined-string-array-index",
    "invalid-array-element-key",
    "deprecated-function",
    "redundant-isset-check",
    "mixed-clone",
    "invalid-array-index",
    "possibly-null-array-access",
    "possibly-null-iterator",
    "false-operand",
    "null-property-access",
    "redundant-key-check",
    "possibly-null-array-index",
    "invalid-property-read",
    "possibly-invalid-clone",
    "ambiguous-instantiation-target",
    "method-access-on-null",
    "null-iterator",
]